export const countryAdjectiveMapping: Record<string, string> = {
  Afghanistan: 'Afghan',
  Albania: 'Albanian',
  Algeria: 'Algerian',
  Andorra: 'Andorran',
  Angola: 'Angolan',
  'Antigua and Barbuda': 'Antiguan',
  Argentina: 'Argentine',
  Armenia: 'Armenian',
  Australia: 'Australian',
  Austria: 'Austrian',
  Azerbaijan: 'Azerbaijani',
  Bahamas: 'Bahamian',
  Bahrain: 'Bahraini',
  Bangladesh: 'Bangladeshi',
  Barbados: 'Barbadian',
  Belarus: 'Belarusian',
  Belgium: 'Belgian',
  Belize: 'Belizean',
  Benin: 'Beninese',
  Bhutan: 'Bhutanese',
  Bolivia: 'Bolivian',
  'Bosnia and Herzegovina': 'Bosnian',
  Botswana: 'Botswanan',
  Brazil: 'Brazilian',
  Brunei: 'Bruneian',
  Bulgaria: 'Bulgarian',
  'Burkina Faso': 'Burkinabe',
  Burundi: 'Burundian',
  Cambodia: 'Cambodian',
  Cameroon: 'Cameroonian',
  Canada: 'Canadian',
  'Cape Verde': 'Cape Verdean',
  'Central African Republic': 'Central African',
  Chad: 'Chadian',
  Chile: 'Chilean',
  China: 'Chinese',
  Colombia: 'Colombian',
  Comoros: 'Comoran',
  'Congo (Brazzaville)': 'Congolese',
  'Congo (Kinshasa)': 'Congolese',
  'Costa Rica': 'Costa Rican',
  Croatia: 'Croatian',
  Cuba: 'Cuban',
  Cyprus: 'Cypriot',
  'Czech Republic': 'Czech',
  Denmark: 'Danish',
  Djibouti: 'Djiboutian',
  Dominica: 'Dominican',
  'Dominican Republic': 'Dominican',
  'East Timor': 'Timorese',
  Ecuador: 'Ecuadorian',
  Egypt: 'Egyptian',
  'El Salvador': 'Salvadoran',
  'Equatorial Guinea': 'Equatorial Guinean',
  Eritrea: 'Eritrean',
  Estonia: 'Estonian',
  Eswatini: 'Swazi',
  Ethiopia: 'Ethiopian',
  Fiji: 'Fijian',
  Finland: 'Finnish',
  France: 'French',
  Gabon: 'Gabonese',
  Gambia: 'Gambian',
  Georgia: 'Georgian',
  Germany: 'German',
  Ghana: 'Ghanaian',
  Greece: 'Greek',
  Grenada: 'Grenadian',
  Guatemala: 'Guatemalan',
  Guinea: 'Guinean',
  'Guinea-Bissau': 'Bissau-Guinean',
  Guyana: 'Guyanese',
  Haiti: 'Haitian',
  Honduras: 'Honduran',
  Hungary: 'Hungarian',
  Iceland: 'Icelandic',
  India: 'Indian',
  Indonesia: 'Indonesian',
  Iran: 'Iranian',
  Iraq: 'Iraqi',
  Ireland: 'Irish',
  Israel: 'Israeli',
  Italy: 'Italian',
  Jamaica: 'Jamaican',
  Japan: 'Japanese',
  Jordan: 'Jordanian',
  Kazakhstan: 'Kazakh',
  Kenya: 'Kenyan',
  Kiribati: 'I-Kiribati',
  'Korea, North': 'North Korean',
  'Korea, South': 'South Korean',
  Kosovo: 'Kosovar',
  Kuwait: 'Kuwaiti',
  Kyrgyzstan: 'Kyrgyz',
  Laos: 'Lao',
  Latvia: 'Latvian',
  Lebanon: 'Lebanese',
  Lesotho: 'Basotho',
  Liberia: 'Liberian',
  Libya: 'Libyan',
  Liechtenstein: 'Liechtensteiner',
  Lithuania: 'Lithuanian',
  Luxembourg: 'Luxembourgish',
  Madagascar: 'Malagasy',
  Malawi: 'Malawian',
  Malaysia: 'Malaysian',
  Maldives: 'Maldivian',
  Mali: 'Malian',
  Malta: 'Maltese',
  'Marshall Islands': 'Marshallese',
  Mauritania: 'Mauritanian',
  Mauritius: 'Mauritian',
  Mexico: 'Mexican',
  Micronesia: 'Micronesian',
  Moldova: 'Moldovan',
  Monaco: 'Monégasque',
  Mongolia: 'Mongolian',
  Montenegro: 'Montenegrin',
  Morocco: 'Moroccan',
  Mozambique: 'Mozambican',
  Myanmar: 'Burmese',
  Namibia: 'Namibian',
  Nauru: 'Nauruan',
  Nepal: 'Nepali',
  Netherlands: 'Dutch',
  'New Zealand': 'New Zealander',
  Nicaragua: 'Nicaraguan',
  Niger: 'Nigerien',
  Nigeria: 'Nigerian',
  'North Macedonia': 'Macedonian',
  Norway: 'Norwegian',
  Oman: 'Omani',
  Pakistan: 'Pakistani',
  Palau: 'Palauan',
  Palestine: 'Palestinian',
  Panama: 'Panamanian',
  'Papua New Guinea': 'Papua New Guinean',
  Paraguay: 'Paraguayan',
  Peru: 'Peruvian',
  Philippines: 'Filipino',
  Poland: 'Polish',
  Portugal: 'Portuguese',
  Qatar: 'Qatari',
  Romania: 'Romanian',
  Russia: 'Russian',
  Rwanda: 'Rwandan',
  'Saint Kitts and Nevis': 'Kittitian',
  'Saint Lucia': 'Saint Lucian',
  'Saint Vincent and the Grenadines': 'Saint Vincentian',
  Samoa: 'Samoan',
  'San Marino': 'Sammarinese',
  'Sao Tome and Principe': 'São Toméan',
  'Saudi Arabia': 'Saudi',
  Senegal: 'Senegalese',
  Serbia: 'Serbian',
  Seychelles: 'Seychellois',
  'Sierra Leone': 'Sierra Leonean',
  Singapore: 'Singaporean',
  Slovakia: 'Slovak',
  Slovenia: 'Slovene',
  'Solomon Islands': 'Solomon Islander',
  Somalia: 'Somali',
  'South Africa': 'South African',
  'South Sudan': 'South Sudanese',
  Spain: 'Spanish',
  'Sri Lanka': 'Sri Lankan',
  Sudan: 'Sudanese',
  Suriname: 'Surinamese',
  Sweden: 'Swedish',
  Switzerland: 'Swiss',
  Syria: 'Syrian',
  Taiwan: 'Taiwanese',
  Tajikistan: 'Tajik',
  Tanzania: 'Tanzanian',
  Thailand: 'Thai',
  Togo: 'Togolese',
  Tonga: 'Tongan',
  'Trinidad and Tobago': 'Trinidadian',
  Tunisia: 'Tunisian',
  Turkey: 'Turkish',
  Turkmenistan: 'Turkmen',
  Tuvalu: 'Tuvaluan',
  Uganda: 'Ugandan',
  Ukraine: 'Ukrainian',
  'United Arab Emirates': 'Emirati',
  'United Kingdom': 'British',
  'United States': 'American',
  Uruguay: 'Uruguayan',
  Uzbekistan: 'Uzbek',
  Vanuatu: 'Ni-Vanuatu',
  'Vatican City': 'Vatican',
  Venezuela: 'Venezuelan',
  Vietnam: 'Vietnamese',
  Yemen: 'Yemeni',
  Zambia: 'Zambian',
  Zimbabwe: 'Zimbabwean',
};
